"""Utility bills (SPEC.md section 15): the meter table read from the bill's own text over the AI's reading, the
confirmation step (and skipping it at upload), and Re-extract from the upload history."""
import pytest

from app.parser.utility_meter import meter_from_text, reconcile
from app.parser.utility_vision import ElectricMeterDetails

TABLE = [
    "METER 352533914                    Read Dates: 09/02/26 - 10/04/26 (32 Days)",
    "DESCRIPTION                     CURRENT READING    PREVIOUS READING     USAGE",
    "On Peak Delivered by Xcel          152 Actual          0 Actual        152 kWh",
    "Off Peak Delivered by Xcel         679 Actual          0 Actual        679 kWh",
    "Total Del by Xcel                  831 Actual          0 Actual        831 kWh",
    "On Pk Delivered by Customer         13 Actual          0 Actual         13 kWh",
    "Off Pk Delivered by Customer       755 Actual          0 Actual        755 kWh",
    "Total Delivered by Customer        768 Actual          0 Actual        768 kWh",
    "On Pk Net Delivered by Xcel        139 Actual          0 Actual        139 kWh",
    "Off Pk Net Delivered by Xcel         0 Actual          0 Actual          0 kWh",
    "Total Net Delivered by Xcel        139 Actual          0 Actual        139 kWh",
    "On Net Generated by Customer         0 Actual          0 Actual          0 kWh",
    "Off Net Generated by Customer       76 Actual          0 Actual         76 kWh",
    "Net Generated by Customer           76 Actual          0 Actual         76 kWh",
]
# what the AI answered for this bill: the off-peak surplus read as 0
AI_METER = dict(grid_import_on_peak_kwh=152, grid_import_off_peak_kwh=679, grid_import_total_kwh=831,
                solar_export_on_peak_kwh=13, solar_export_off_peak_kwh=755, solar_export_total_kwh=768,
                net_on_peak_kwh=139, net_off_peak_kwh=0, net_total_kwh=139, net_generated_on_peak_kwh=0,
                net_generated_off_peak_kwh=0, net_generated_total_kwh=0, on_peak_rate=0.21277, on_peak_charge=25.88,
                off_peak_rate=0.07884, off_peak_charge=0.0)


def test_meter_rows_from_the_text():
    got = meter_from_text("\n".join(TABLE))
    assert len(got) == 12
    assert (got["grid_import_total_kwh"], got["solar_export_off_peak_kwh"], got["net_total_kwh"]) == (831, 755, 139)
    assert (got["net_generated_on_peak_kwh"], got["net_generated_off_peak_kwh"], got["net_generated_total_kwh"]) == (0, 76, 76)
    # two meters disagreeing on a row: that row isn't used
    two = meter_from_text("\n".join(TABLE + ["Off Net Generated by Customer   12 Actual  0 Actual   12 kWh"]))
    assert "net_generated_off_peak_kwh" not in two and two["net_generated_total_kwh"] == 76


def test_printed_figures_win_and_the_arithmetic_fills_the_rest():
    m = ElectricMeterDetails(**AI_METER)
    changes = reconcile(m, meter_from_text("\n".join(TABLE)))
    assert (m.net_generated_off_peak_kwh, m.net_generated_total_kwh) == (76, 76)
    assert changes == ["Net generated by you, off-peak: 0 → 76 (as printed on the bill)",
                       "Net generated by you, total: 0 → 76 (as printed on the bill)"]
    assert m.on_peak_rate == 0.21277                                   # rates and charges untouched
    # without the table in the text: the same answer from the meter arithmetic
    m = ElectricMeterDetails(**AI_METER)
    changes = reconcile(m, {})
    assert (m.net_generated_off_peak_kwh, m.net_generated_total_kwh, m.net_off_peak_kwh) == (76, 76, 0)
    assert len(changes) == 2
    assert reconcile(m, {}) == []                                      # nothing left to change


@pytest.fixture
def fake_xcel(monkeypatch):
    from app.parser import utility_pipeline as up
    from app.parser.utility_vision import ParsedUtilityBill, UtilityVisionResult
    calls = []

    def fake(pdf, url, model, on_step=None, provider=None, notes=""):
        calls.append(notes)
        return UtilityVisionResult(bills=[ParsedUtilityBill(
            utility_type="electric", provider="Xcel Energy", period_start_date="2026-09-02",
            period_end_date="2026-10-04", usage_amount=831, usage_unit="kWh", cost=68.86, due_date="2026-10-27",
            account_number_last4="6019", electric_meter_details=ElectricMeterDetails(**AI_METER))], raw_response="{}")
    monkeypatch.setattr(up, "extract_vision_utility", fake)
    return calls


def _upload(env, skip=False):
    lines = ["Xcel Energy", "Electricity Charges Total $68.86", "Amount due by 10/27/26 $68.86"] + TABLE
    with open(env.pdf(lines), "rb") as f:
        data = {"provider": "Xcel Energy"}
        if skip:
            data["skip_confirmation"] = "1"
        r = env.post("utility-upload", data=data, files={"files": ("xcel.pdf", f.read(), "application/pdf")}).json()
    bid = r["results"][0]["utility_bill_id"]
    return bid, env.wait_status("utility_bills", bid)


def test_waits_for_confirmation_with_the_meter_corrected(env, fake_xcel):
    bid, row = _upload(env)
    assert (row["status"], row["review_status"], row["error_message"]) == ("pending_review", "clean", None)
    assert row["pdf_path"] and "Net generated by you, off-peak: 0 → 76" in row["corrections"]
    with env.db() as c:
        meter = c.execute("SELECT * FROM electric_meter_details WHERE utility_bill_id=?", (bid,)).fetchone()
    assert (meter["net_generated_off_peak_kwh"], meter["net_generated_total_kwh"]) == (76, 76)
    history = env.get("utilities?tab=upload").text
    assert "Awaiting confirmation" in history and "Check &amp; confirm" in history
    assert f'data-url="utility-reextract?id={bid}' in history
    page = env.get(f"utility-review?id={bid}").text
    assert "Confirm: Xcel Energy electric bill" in page and "Taken from the bill's own meter table" in page
    assert 'name="meter_net_generated_off_peak_kwh" value="76.0"' in page
    # Re-extract from the history's dialog (htmx, id in the address): the page reloads
    r = env.post(f"utility-reextract?id={bid}", data={"notes": "Off-peak generated is 76."}, headers={"HX-Request": "true"})
    assert r.status_code == 200 and r.headers.get("HX-Refresh") == "true"
    row = env.wait_status("utility_bills", bid)
    assert fake_xcel[-1] == "Off-peak generated is 76." and row["status"] == "pending_review"
    # Confirm: complete, the PDF goes
    form = {"id": bid, "period_start_date": "2026-09-02", "period_end_date": "2026-10-04", "cost": "68.86",
            "usage_amount": "831", "usage_unit": "kWh", "meter_net_generated_off_peak_kwh": "76"}
    assert env.post("utility-resolve", data=form).status_code == 303
    with env.db() as c:
        done = c.execute("SELECT status, pdf_path FROM utility_bills WHERE id=?", (bid,)).fetchone()
    assert done["status"] == "complete" and done["pdf_path"] is None


def test_skipping_confirmation_completes_at_once(env, fake_xcel):
    bid, row = _upload(env, skip=True)
    assert row["status"] == "complete" and row["needs_confirmation"] == 0 and row["pdf_path"] is None
    assert "off-peak: 0 → 76" in row["corrections"]
    assert "Skip the confirmation step" in env.get("utilities?tab=upload").text
