"""The electric meter table, read from the bill's own text and used to check the AI's reading (SPEC.md section 15).

Xcel prints the on/off-peak meter readings as a table (pdftotext -layout keeps each row on one line):

    On Peak Delivered by Xcel        152 Actual      0 Actual     152 kWh
    Off Net Generated by Customer     76 Actual      0 Actual      76 kWh

`meter_from_text` finds those rows by their labels and takes each row's USAGE (the number before "kWh" at the end).
`reconcile` then puts the printed figures over the AI's (the model sometimes copies the example's zeros, e.g. a
76 kWh off-peak surplus read as 0), and fills or corrects the rest from the meter arithmetic:

    net delivered  = import - export   when import is larger, else 0
    net generated  = export - import   when export is larger, else 0
    total          = on-peak + off-peak

A printed figure is never changed by the arithmetic. Each change is described in plain words for the review page.
"""
import re

PERIODS = ("on_peak", "off_peak", "total")
_LABEL = {
    "grid_import": "delivered by Xcel", "solar_export": "delivered by you",
    "net": "net delivered by Xcel", "net_generated": "net generated by you",
}
_PERIOD_WORD = {"on_peak": "on-peak", "off_peak": "off-peak", "total": "total"}
_FIELD_RE = re.compile(r"^(grid_import|solar_export|net_generated|net)_(on_peak|off_peak|total)_kwh$")
_KWH = re.compile(r"([\d][\d,]*(?:\.\d+)?)\s*kwh\b", re.I)


def _field(kind: str, period: str) -> str:
    return f"{kind}_{period}_kwh"


def _classify(label: str) -> str | None:
    """A meter row's label → its field name, or None when it isn't one of the twelve rows."""
    t = " ".join(label.lower().replace(".", " ").split())
    if "by xcel" not in t and "by customer" not in t:
        return None
    if t.startswith("on "):
        period = "on_peak"
    elif t.startswith("off "):
        period = "off_peak"
    elif t.startswith("total ") or t.startswith("net generated"):
        period = "total"
    else:
        return None
    if "generated" in t:
        kind = "net_generated"
    elif " net " in f" {t} ":
        kind = "net"
    elif "by xcel" in t and re.search(r"\bdel(ivered)?\b", t):
        kind = "grid_import"
    elif "by customer" in t and re.search(r"\bdel(ivered)?\b", t):
        kind = "solar_export"
    else:
        return None
    return _field(kind, period)


def meter_from_text(text: str) -> dict[str, float]:
    """{field: kWh} for the meter rows printed in the bill's text. A row printed twice with different figures (two
    meters on one bill) is left out, so only what the bill says unambiguously is used."""
    found: dict[str, float] = {}
    clash: set[str] = set()
    for line in (text or "").splitlines():
        m = re.match(r"\s*([A-Za-z][A-Za-z .]*?(?:by\s+(?:Xcel|Customer)))\b(.*)$", line, re.I)
        if not m:
            continue
        field = _classify(m.group(1))
        if field is None:
            continue
        nums = _KWH.findall(m.group(2))
        if not nums:
            continue
        value = float(nums[-1].replace(",", ""))
        if field in found and found[field] != value:
            clash.add(field)
        found[field] = value
    return {k: v for k, v in found.items() if k not in clash}


def _fmt(v) -> str:
    if v is None:
        return "blank"
    return str(int(v)) if float(v).is_integer() else f"{v:g}"


def reconcile(meter, printed: dict[str, float]) -> list[str]:
    """Correct `meter` (an object with the *_kwh attributes) in place; returns what was changed, in words."""
    changes: list[str] = []
    fixed: set[str] = set()

    def put(field: str, value: float, why: str) -> None:
        old = getattr(meter, field)
        if old is not None and abs(float(old) - value) < 1e-6:
            return
        setattr(meter, field, value)
        kind, period = _FIELD_RE.match(field).groups()
        changes.append(f"{_LABEL[kind].capitalize()}, {_PERIOD_WORD[period]}: {_fmt(old)} → {_fmt(value)} ({why})")

    for field, value in printed.items():
        if hasattr(meter, field):
            put(field, value, "as printed on the bill")
            fixed.add(field)

    def get(field):
        v = getattr(meter, field)
        return None if v is None else float(v)

    for period in ("on_peak", "off_peak"):
        imp, exp = get(_field("grid_import", period)), get(_field("solar_export", period))
        if imp is None or exp is None:
            continue
        for kind, value in (("net", max(0.0, imp - exp)), ("net_generated", max(0.0, exp - imp))):
            f = _field(kind, period)
            if f not in fixed:
                put(f, value, "from what Xcel delivered and what you delivered")
    for kind in _LABEL:
        on, off, total = (_field(kind, p) for p in PERIODS)
        if total not in fixed and get(on) is not None and get(off) is not None:
            put(total, get(on) + get(off), "on-peak plus off-peak")
    return changes
